const String api_url = "http://192.168.43.171:8080";
const String api_race_results = api_url + "/results?year=2020&round=";
const String api_driver_standings = api_url + "/standings/drivers";
const String api_constructor_standings = api_url + "/standings/constructors";
const String api_driver_credits = api_url + "/league/credits?year=2020&round=";
const String api_race_schedule = api_url + "/schedule";
const String api_join_league = api_url + "/league/join";
const String api_user_leagues = api_url + "/league/user";
const String api_leaderboard = api_url + "/leaderboard";
const String cache_race_schedule = "grandprix";
const String cache_user_leaguess = "leagues";
const String cache_driver_standings = "driverStandings";
const String cache_constructor_standings = "constructorStandings";
const String cache_race_results = "result#";
const String cache_user_leagues = "userLeagues";
const String cache_join_league = "league#";
const String cache_leaderboard = "leaderboard";
